### ISSUE TITLE
get.docker.io is more or less deprecated...

### ISSUE THREAD

**Issue by robbyoconnor** [andrewrothstein/ansible-docker#7]
It appears that Docker no longer maintains or recommends the use of https://get.docker.io

This may break in undetermined ways at some time in the future...

**Comment by andrewrothstein** [comment]
thanks for the tip! what's the suggested way to install Docker? with the OS package manager?

**Comment by andrewrothstein** [comment]
https://docs.docker.com/engine/installation/linux/rhel/
https://docs.docker.com/engine/installation/linux/ubuntulinux/
https://docs.docker.com/engine/installation/linux/centos/
https://docs.docker.com/engine/installation/linux/fedora/

**Comment by robbyoconnor** [comment]
@andrewrothstein -- was that to me, or to you? In either case the get.docker.io script is more or less deprecated...but yeh you add their package repos.. and then use the OS package manager

**Comment by andrewrothstein** [comment]
that was to me. working on refactoring this.

**Comment by robbyoconnor** [comment]
I liked your role since it actually handles the case of the init system being systemd -- so many roles ignore this case.

**Comment by andrewrothstein** [comment]
I published a new version of the role (v5.0.0) to the galaxy that doesn't use the get.docker.io hack. I'd appreciate any testing feedback you can offer. Thanks for pointing this out!
